listen:
  host: 0.0.0.0
  port: 31337

stations:
  - id: "fip"
    icy:
      name: "FIP (proxy)"
      metaint: 16384
      bitrate_hint_kbps: 128
    source:
      url: "https://icecast.radiofrance.fr/fip-midfi.mp3?id=radiofrance"
      request_headers:
        Icy-MetaData: "0"
      connect_timeout_ms: 5000
      read_timeout_ms: 15000
    metadata:
      url: "https://fip-metadata.fly.dev/api/metadata/fip"
      poll_ms: 3000
      build:
        format: "StreamTitle='{artist} - {title}';Artist='{artist}';Title='{title}';Album='{album}';Artwork='{artwork}';StreamUrl='http://localhost:31337/fip/cover';"
        strip_single_quotes: true
        normalize_whitespace: true
        fallback_key_order:
          - now.secondLine.title       # artist
          - now.firstLine.title        # title
          - now.song.release.title     # album
          - now.visual.src             # artwork (FIP uses visual.src for cover images)
          - now.song.year              # year
          - now.song.release.label     # label
    buffering:
      ring_bytes: 262144

logging:
  level: info
  json: false
