listen:
  host: 0.0.0.0
  port: 31337

stations:
  - id: "fip"
    icy:
      name: "FIP (proxy)"
      metaint: 16384
      bitrate_hint_kbps: 128
    source:
      url: "https://icecast.radiofrance.fr/fip-hifi.aac"
      request_headers:
        Icy-MetaData: "0"
      connect_timeout_ms: 5000
      read_timeout_ms: 15000
    metadata:
      url: "https://fip-metadata.fly.dev/"
      poll_ms: 3000
      build:
        format: "StreamTitle='{artist} - {title}';"
        strip_single_quotes: true
        normalize_whitespace: true
    buffering:
      ring_bytes: 262144

  - id: "nts"
    icy:
      name: "NTS Radio 1 (proxy)"
      metaint: 16384
      bitrate_hint_kbps: 128
    source:
      url: "https://stream-mixtape-geo.ntslive.net/stream"
      request_headers:
        Icy-MetaData: "0"
      connect_timeout_ms: 5000
      read_timeout_ms: 15000
    metadata:
      url: "https://www.nts.live/api/v2/live"
      poll_ms: 5000
      build:
        format: "StreamTitle='{artist} - {title}';"
        strip_single_quotes: true
        normalize_whitespace: true
    buffering:
      ring_bytes: 262144

logging:
  level: info
  json: false
